In [2]:
import pandas as pd

comp = pd.read_csv('race_results/summary.csv')

comp

,strata_race,n,n_train,n_test,enet_best_params,enet_r2,enet_r2_se,enet_mse,xgb_best_params,xgb_r2,xgb_r2_se,xgb_mse
0,White or Caucasian_pre_diabetes_lifestyle_cont...,218,174,44,"{'enet__alpha': 0.1, 'enet__l1_ratio': 0.9}",0.829876,0.041586,0.280817,"{'colsample_bytree': 0.7, 'learning_rate': 0.0...",0.787166,0.053676,0.351317
1,Black or African American_healthy,115,92,23,"{'enet__alpha': 0.1, 'enet__l1_ratio': 0.3}",0.679564,0.127076,0.215951,"{'colsample_bytree': 1.0, 'learning_rate': 0.0...",0.553512,0.152980,0.300900
2,Asian_oral_medication_and_or_non_insulin_injec...,147,117,30,"{'enet__alpha': 0.1, 'enet__l1_ratio': 0.1}",0.619193,0.170219,0.359152,"{'colsample_bytree': 1.0, 'learning_rate': 0.1...",0.561057,0.190187,0.413982
3,White or Caucasian_healthy,395,316,79,"{'enet__alpha': 0.001, 'enet__l1_ratio': 0.1}",0.405718,0.334331,0.355162,"{'colsample_bytree': 1.0, 'learning_rate': 0.0...",0.446190,0.446740,0.330975
4,White or Caucasian_oral_medication_and_or_non_...,287,229,58,"{'enet__alpha': 0.1, 'enet__l1_ratio': 0.3}",0.375789,0.528235,0.430616,"{'colsample_bytree': 1.0, 'learning_rate': 0.0...",0.631557,0.208723,0.254172
5,Asian_pre_diabetes_lifestyle_controlled,177,141,36,"{'enet__alpha': 0.1, 'enet__l1_ratio': 0.9}",0.907426,0.080966,0.081021,"{'colsample_bytree': 1.0, 'learning_rate': 0.0...",0.794480,0.111327,0.179871
6,White or Caucasian_insulin_dependent,102,81,21,"{'enet__alpha': 1, 'enet__l1_ratio': 0.3}",0.219059,0.457374,2.206411,"{'colsample_bytree': 0.7, 'learning_rate': 0.0...",0.087901,1.056980,2.576976
7,Black or African American_oral_medication_and_...,175,140,35,"{'enet__alpha': 0.1, 'enet__l1_ratio': 0.1}",0.661057,0.122689,0.421584,"{'colsample_bytree': 0.7, 'learning_rate': 0.1...",0.637378,0.139075,0.451036
8,Black or African American_pre_diabetes_lifesty...,113,90,23,"{'enet__alpha': 0.1, 'enet__l1_ratio': 1.0}",0.775985,0.053874,0.318874,"{'colsample_bytree': 1.0, 'learning_rate': 0.1...",0.559286,0.301055,0.627335
9,Asian_healthy,200,160,40,"{'enet__alpha': 0.01, 'enet__l1_ratio': 1.0}",0.808171,0.048837,0.341816,"{'colsample_bytree': 0.7, 'learning_rate': 0.0...",0.459939,0.142034,0.962321

In [1]:
import pandas as pd

comp = pd.read_csv('weight_class_results/summary.csv')

comp

,strata_weight_class,n,n_train,n_test,enet_best_params,enet_r2,enet_r2_se,enet_mse,xgb_best_params,xgb_r2,xgb_r2_se,xgb_mse
0,Normal_pre_diabetes_lifestyle_controlled,156,124,32,"{'enet__alpha': 0.1, 'enet__l1_ratio': 0.5}",0.660449,0.058058,0.169622,"{'colsample_bytree': 0.7, 'learning_rate': 0.0...",0.586234,0.086562,0.206696
1,Obesity_healthy,231,184,47,"{'enet__alpha': 0.1, 'enet__l1_ratio': 0.5}",0.694630,0.035525,1.367872,"{'colsample_bytree': 1.0, 'learning_rate': 0.0...",0.466763,0.125751,2.388576
2,Overweight_oral_medication_and_or_non_insulin_...,210,168,42,"{'enet__alpha': 0.01, 'enet__l1_ratio': 1.0}",0.421842,0.588579,0.233382,"{'colsample_bytree': 1.0, 'learning_rate': 0.1...",0.622680,0.324722,0.152310
3,Overweight_healthy,271,216,55,"{'enet__alpha': 0.01, 'enet__l1_ratio': 1.0}",0.785866,0.104075,0.111262,"{'colsample_bytree': 1.0, 'learning_rate': 0.0...",0.747244,0.087728,0.131329
4,Overweight_pre_diabetes_lifestyle_controlled,185,148,37,"{'enet__alpha': 0.1, 'enet__l1_ratio': 1.0}",0.863116,0.212602,0.098121,"{'colsample_bytree': 0.7, 'learning_rate': 0.0...",0.746209,0.282194,0.181921
5,Normal_oral_medication_and_or_non_insulin_inje...,131,104,27,"{'enet__alpha': 0.1, 'enet__l1_ratio': 0.5}",0.739019,0.065726,0.076987,"{'colsample_bytree': 1.0, 'learning_rate': 0.0...",0.617735,0.110651,0.112764
6,Obesity_oral_medication_and_or_non_insulin_inj...,322,257,65,"{'enet__alpha': 0.1, 'enet__l1_ratio': 0.5}",0.573004,0.112065,0.812397,"{'colsample_bytree': 1.0, 'learning_rate': 0.1...",0.673306,0.144609,0.621565
7,Obesity_insulin_dependent,151,120,31,"{'enet__alpha': 0.1, 'enet__l1_ratio': 0.7}",0.186580,0.351500,0.901211,"{'colsample_bytree': 0.7, 'learning_rate': 0.0...",0.155876,0.220572,0.935229
8,Normal_healthy,242,193,49,"{'enet__alpha': 0.1, 'enet__l1_ratio': 0.3}",0.765239,0.069160,0.072144,"{'colsample_bytree': 1.0, 'learning_rate': 0.1...",0.670125,0.099690,0.101373
9,Obesity_pre_diabetes_lifestyle_controlled,203,162,41,"{'enet__alpha': 0.1, 'enet__l1_ratio': 1.0}",0.733229,0.055892,0.387898,"{'colsample_bytree': 1.0, 'learning_rate': 0.1...",0.682163,0.117372,0.462150

In [4]:
import pandas as pd

comp = pd.read_csv('sex_results/summary.csv')

comp

,strata_sex,n,n_train,n_test,enet_best_params,enet_r2,enet_r2_se,enet_mse,xgb_best_params,xgb_r2,xgb_r2_se,xgb_mse
0,Female_pre_diabetes_lifestyle_controlled,351,280,71,"{'enet__alpha': 0.1, 'enet__l1_ratio': 0.9}",0.733317,0.041644,0.355054,"{'colsample_bytree': 1.0, 'learning_rate': 0.0...",0.798086,0.047278,0.268822
1,Male_healthy,295,236,59,"{'enet__alpha': 0.1, 'enet__l1_ratio': 0.7}",0.399333,0.352378,0.270846,"{'colsample_bytree': 1.0, 'learning_rate': 0.0...",0.736470,0.139238,0.118828
2,Male_oral_medication_and_or_non_insulin_inject...,307,245,62,"{'enet__alpha': 0.1, 'enet__l1_ratio': 0.3}",0.659039,0.065237,0.290508,"{'colsample_bytree': 1.0, 'learning_rate': 0.0...",0.768949,0.062661,0.196862
3,Male_insulin_dependent,122,97,25,"{'enet__alpha': 1, 'enet__l1_ratio': 0.1}",0.294430,0.437420,1.292938,"{'colsample_bytree': 0.7, 'learning_rate': 0.0...",0.233705,0.517571,1.404215
4,Female_healthy,464,371,93,"{'enet__alpha': 0.1, 'enet__l1_ratio': 1.0}",0.810287,0.051980,0.121773,"{'colsample_bytree': 1.0, 'learning_rate': 0.0...",0.792012,0.038760,0.133503
5,Male_pre_diabetes_lifestyle_controlled,198,158,40,"{'enet__alpha': 0.1, 'enet__l1_ratio': 0.3}",0.617912,0.206408,0.161889,"{'colsample_bytree': 1.0, 'learning_rate': 0.0...",0.700886,0.163487,0.126733
6,Female_insulin_dependent,124,99,25,"{'enet__alpha': 1, 'enet__l1_ratio': 0.1}",0.224980,0.152955,0.957092,"{'colsample_bytree': 0.7, 'learning_rate': 0.0...",0.228553,0.141737,0.952680
7,Female_oral_medication_and_or_non_insulin_inje...,356,284,72,"{'enet__alpha': 0.1, 'enet__l1_ratio': 0.3}",0.599361,0.053356,0.853190,"{'colsample_bytree': 0.7, 'learning_rate': 0.0...",0.632097,0.106157,0.783477